/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ChildIndexRouteImport } from './routes/child.index'
import { Route as ChildBuddyRouteImport } from './routes/child.buddy'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherThemesRouteImport } from './routes/_authenticated/teacher.themes'
import { Route as ChildPhonicsIndexRouteImport } from './routes/child.phonics.index'
import { Route as ChildPhonicsDecodeRouteImport } from './routes/child.phonics.decode'
import { Route as ChildPhonicsPronounceRouteImport } from './routes/child.phonics.pronounce'
import { Route as ChildPhonicsReadRouteImport } from './routes/child.phonics.read'
import { Route as ChildPhonicsSoundRouteImport } from './routes/child.phonics.sound'
import { Route as ChildPhonicsTraceRouteImport } from './routes/child.phonics.trace'
import { Route as ChildThemeThemeSlugRouteImport } from './routes/child.theme.$themeSlug'
import { Route as ChildWelcomeCharRouteImport } from './routes/child.welcome.$char'
import { Route as AuthenticatedTeacherClassClassIdRouteImport } from './routes/_authenticated/teacher.class.$classId'
import { Route as AuthenticatedTeacherReportChildIdRouteImport } from './routes/_authenticated/teacher.report.$childId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildIndexRoute = ChildIndexRouteImport.update({
  id: '/child/',
  path: '/child/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildBuddyRoute = ChildBuddyRouteImport.update({
  id: '/child/buddy',
  path: '/child/buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherThemesRoute =
  AuthenticatedTeacherThemesRouteImport.update({
    id: '/teacher/themes',
    path: '/teacher/themes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ChildPhonicsIndexRoute = ChildPhonicsIndexRouteImport.update({
  id: '/child/phonics/',
  path: '/child/phonics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildPhonicsDecodeRoute = ChildPhonicsDecodeRouteImport.update({
  id: '/child/phonics/decode',
  path: '/child/phonics/decode',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildPhonicsPronounceRoute = ChildPhonicsPronounceRouteImport.update({
  id: '/child/phonics/pronounce',
  path: '/child/phonics/pronounce',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildPhonicsReadRoute = ChildPhonicsReadRouteImport.update({
  id: '/child/phonics/read',
  path: '/child/phonics/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildPhonicsSoundRoute = ChildPhonicsSoundRouteImport.update({
  id: '/child/phonics/sound',
  path: '/child/phonics/sound',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildPhonicsTraceRoute = ChildPhonicsTraceRouteImport.update({
  id: '/child/phonics/trace',
  path: '/child/phonics/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildThemeThemeSlugRoute = ChildThemeThemeSlugRouteImport.update({
  id: '/child/theme/$themeSlug',
  path: '/child/theme/$themeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildWelcomeCharRoute = ChildWelcomeCharRouteImport.update({
  id: '/child/welcome/$char',
  path: '/child/welcome/$char',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherClassClassIdRoute =
  AuthenticatedTeacherClassClassIdRouteImport.update({
    id: '/teacher/class/$classId',
    path: '/teacher/class/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherReportChildIdRoute =
  AuthenticatedTeacherReportChildIdRouteImport.update({
    id: '/teacher/report/$childId',
    path: '/teacher/report/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/role': typeof RoleRoute
  '/child/buddy': typeof ChildBuddyRoute
  '/child/': typeof ChildIndexRoute
  '/teacher/themes': typeof AuthenticatedTeacherThemesRoute
  '/child/phonics/decode': typeof ChildPhonicsDecodeRoute
  '/child/phonics/pronounce': typeof ChildPhonicsPronounceRoute
  '/child/phonics/read': typeof ChildPhonicsReadRoute
  '/child/phonics/sound': typeof ChildPhonicsSoundRoute
  '/child/phonics/trace': typeof ChildPhonicsTraceRoute
  '/child/theme/$themeSlug': typeof ChildThemeThemeSlugRoute
  '/child/welcome/$char': typeof ChildWelcomeCharRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/child/phonics/': typeof ChildPhonicsIndexRoute
  '/teacher/class/$classId': typeof AuthenticatedTeacherClassClassIdRoute
  '/teacher/report/$childId': typeof AuthenticatedTeacherReportChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/role': typeof RoleRoute
  '/child/buddy': typeof ChildBuddyRoute
  '/child': typeof ChildIndexRoute
  '/teacher/themes': typeof AuthenticatedTeacherThemesRoute
  '/child/phonics/decode': typeof ChildPhonicsDecodeRoute
  '/child/phonics/pronounce': typeof ChildPhonicsPronounceRoute
  '/child/phonics/read': typeof ChildPhonicsReadRoute
  '/child/phonics/sound': typeof ChildPhonicsSoundRoute
  '/child/phonics/trace': typeof ChildPhonicsTraceRoute
  '/child/theme/$themeSlug': typeof ChildThemeThemeSlugRoute
  '/child/welcome/$char': typeof ChildWelcomeCharRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/child/phonics': typeof ChildPhonicsIndexRoute
  '/teacher/class/$classId': typeof AuthenticatedTeacherClassClassIdRoute
  '/teacher/report/$childId': typeof AuthenticatedTeacherReportChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/role': typeof RoleRoute
  '/child/buddy': typeof ChildBuddyRoute
  '/child/': typeof ChildIndexRoute
  '/_authenticated/teacher/themes': typeof AuthenticatedTeacherThemesRoute
  '/child/phonics/decode': typeof ChildPhonicsDecodeRoute
  '/child/phonics/pronounce': typeof ChildPhonicsPronounceRoute
  '/child/phonics/read': typeof ChildPhonicsReadRoute
  '/child/phonics/sound': typeof ChildPhonicsSoundRoute
  '/child/phonics/trace': typeof ChildPhonicsTraceRoute
  '/child/theme/$themeSlug': typeof ChildThemeThemeSlugRoute
  '/child/welcome/$char': typeof ChildWelcomeCharRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/child/phonics/': typeof ChildPhonicsIndexRoute
  '/_authenticated/teacher/class/$classId': typeof AuthenticatedTeacherClassClassIdRoute
  '/_authenticated/teacher/report/$childId': typeof AuthenticatedTeacherReportChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/role'
    | '/child/buddy'
    | '/child/'
    | '/teacher/themes'
    | '/child/phonics/decode'
    | '/child/phonics/pronounce'
    | '/child/phonics/read'
    | '/child/phonics/sound'
    | '/child/phonics/trace'
    | '/child/theme/$themeSlug'
    | '/child/welcome/$char'
    | '/teacher/'
    | '/child/phonics/'
    | '/teacher/class/$classId'
    | '/teacher/report/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/role'
    | '/child/buddy'
    | '/child'
    | '/teacher/themes'
    | '/child/phonics/decode'
    | '/child/phonics/pronounce'
    | '/child/phonics/read'
    | '/child/phonics/sound'
    | '/child/phonics/trace'
    | '/child/theme/$themeSlug'
    | '/child/welcome/$char'
    | '/teacher'
    | '/child/phonics'
    | '/teacher/class/$classId'
    | '/teacher/report/$childId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/role'
    | '/child/buddy'
    | '/child/'
    | '/_authenticated/teacher/themes'
    | '/child/phonics/decode'
    | '/child/phonics/pronounce'
    | '/child/phonics/read'
    | '/child/phonics/sound'
    | '/child/phonics/trace'
    | '/child/theme/$themeSlug'
    | '/child/welcome/$char'
    | '/_authenticated/teacher/'
    | '/child/phonics/'
    | '/_authenticated/teacher/class/$classId'
    | '/_authenticated/teacher/report/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RoleRoute: typeof RoleRoute
  ChildBuddyRoute: typeof ChildBuddyRoute
  ChildIndexRoute: typeof ChildIndexRoute
  ChildPhonicsDecodeRoute: typeof ChildPhonicsDecodeRoute
  ChildPhonicsPronounceRoute: typeof ChildPhonicsPronounceRoute
  ChildPhonicsReadRoute: typeof ChildPhonicsReadRoute
  ChildPhonicsSoundRoute: typeof ChildPhonicsSoundRoute
  ChildPhonicsTraceRoute: typeof ChildPhonicsTraceRoute
  ChildThemeThemeSlugRoute: typeof ChildThemeThemeSlugRoute
  ChildWelcomeCharRoute: typeof ChildWelcomeCharRoute
  ChildPhonicsIndexRoute: typeof ChildPhonicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/': {
      id: '/child/'
      path: '/child'
      fullPath: '/child/'
      preLoaderRoute: typeof ChildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/buddy': {
      id: '/child/buddy'
      path: '/child/buddy'
      fullPath: '/child/buddy'
      preLoaderRoute: typeof ChildBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/themes': {
      id: '/_authenticated/teacher/themes'
      path: '/teacher/themes'
      fullPath: '/teacher/themes'
      preLoaderRoute: typeof AuthenticatedTeacherThemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/child/phonics/': {
      id: '/child/phonics/'
      path: '/child/phonics'
      fullPath: '/child/phonics/'
      preLoaderRoute: typeof ChildPhonicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/phonics/decode': {
      id: '/child/phonics/decode'
      path: '/child/phonics/decode'
      fullPath: '/child/phonics/decode'
      preLoaderRoute: typeof ChildPhonicsDecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/phonics/pronounce': {
      id: '/child/phonics/pronounce'
      path: '/child/phonics/pronounce'
      fullPath: '/child/phonics/pronounce'
      preLoaderRoute: typeof ChildPhonicsPronounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/phonics/read': {
      id: '/child/phonics/read'
      path: '/child/phonics/read'
      fullPath: '/child/phonics/read'
      preLoaderRoute: typeof ChildPhonicsReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/phonics/sound': {
      id: '/child/phonics/sound'
      path: '/child/phonics/sound'
      fullPath: '/child/phonics/sound'
      preLoaderRoute: typeof ChildPhonicsSoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/phonics/trace': {
      id: '/child/phonics/trace'
      path: '/child/phonics/trace'
      fullPath: '/child/phonics/trace'
      preLoaderRoute: typeof ChildPhonicsTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/theme/$themeSlug': {
      id: '/child/theme/$themeSlug'
      path: '/child/theme/$themeSlug'
      fullPath: '/child/theme/$themeSlug'
      preLoaderRoute: typeof ChildThemeThemeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/welcome/$char': {
      id: '/child/welcome/$char'
      path: '/child/welcome/$char'
      fullPath: '/child/welcome/$char'
      preLoaderRoute: typeof ChildWelcomeCharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/class/$classId': {
      id: '/_authenticated/teacher/class/$classId'
      path: '/teacher/class/$classId'
      fullPath: '/teacher/class/$classId'
      preLoaderRoute: typeof AuthenticatedTeacherClassClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/report/$childId': {
      id: '/_authenticated/teacher/report/$childId'
      path: '/teacher/report/$childId'
      fullPath: '/teacher/report/$childId'
      preLoaderRoute: typeof AuthenticatedTeacherReportChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTeacherThemesRoute: typeof AuthenticatedTeacherThemesRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeacherClassClassIdRoute: typeof AuthenticatedTeacherClassClassIdRoute
  AuthenticatedTeacherReportChildIdRoute: typeof AuthenticatedTeacherReportChildIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTeacherThemesRoute: AuthenticatedTeacherThemesRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedTeacherClassClassIdRoute: AuthenticatedTeacherClassClassIdRoute,
  AuthenticatedTeacherReportChildIdRoute:
    AuthenticatedTeacherReportChildIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RoleRoute: RoleRoute,
  ChildBuddyRoute: ChildBuddyRoute,
  ChildIndexRoute: ChildIndexRoute,
  ChildPhonicsDecodeRoute: ChildPhonicsDecodeRoute,
  ChildPhonicsPronounceRoute: ChildPhonicsPronounceRoute,
  ChildPhonicsReadRoute: ChildPhonicsReadRoute,
  ChildPhonicsSoundRoute: ChildPhonicsSoundRoute,
  ChildPhonicsTraceRoute: ChildPhonicsTraceRoute,
  ChildThemeThemeSlugRoute: ChildThemeThemeSlugRoute,
  ChildWelcomeCharRoute: ChildWelcomeCharRoute,
  ChildPhonicsIndexRoute: ChildPhonicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
